//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by CheckProtocol.rc
//
#define IDC_BUTTON_FINDDLG_QUITE        3
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_CHECKPROTOCOL_DIALOG        102
#define IDR_MAINFRAME                   128
#define IDR_MENU1                       129
#define IDD_DIALOG_ADD_WEBRULE          130
#define IDD_DIALOG_ADD_PACKRULE         131
#define IDD_DIALOG_LOGINTEST            132
#define IDD_DIALOG_CAPTURE_PACKINFO     133
#define IDB_BITMAP1                     136
#define IDB_BITMAP2                     137
#define IDD_DIALOG1                     138
#define IDD_DIALOG_FIND_PACKRUEL        139
#define IDD_DIALOG_DOWNLOAD             140
#define IDD_DIALOG_UPDATA_DOWNLOAD      141
#define IDD_DIALOG2                     142
#define IDC_LIST_WEB_RULE               1000
#define IDC_EDIT_WEB_ITEMNAME           1001
#define IDC_EDIT_WEB_URL                1002
#define IDC_EDIT_WEB_OK_BUTTON_NAME     1003
#define IDC_EDIT_WEB_PASSWORD_KEY       1004
#define IDC_EDIT_WEB_OPERATE            1005
#define IDC_EDIT_WEB_USERNAME           1006
#define IDC_EDIT_WEB_PASSWORD           1007
#define IDC_EDIT_WEB_USERNAME_KEY       1008
#define IDC_EDIT_WEB_SEND_CONTENT       1010
#define IDC_EDIT_WEB_REMARK             1011
#define IDC_EDIT_WEB_SENDKEY            1011
#define IDC_BUTTON1                     1012
#define IDC_BUTTON_REFRESH              1012
#define ID_BUTTON_PACKINFO              1012
#define IDC_BUTTON_QUIT                 1012
#define IDC_BUTTON_FINDDLG_FILTER       1012
#define IDC_BUTTON_DOWNLOAD_SAVE        1012
#define IDC_BUTTON2                     1013
#define IDC_BUTTON_CLEAN                1013
#define IDC_BUTTON_CLEAR                1013
#define IDC_LIST_PACK_RULE              1014
#define IDC_EDIT_PACK_ITEMNAME          1015
#define IDC_EDIT_PACK_USERNAME          1016
#define IDC_EDIT_PACK_PASSWORD          1017
#define IDC_EDIT_PACK_ENDUSERNAME       1017
#define IDC_EDIT_PACK_USERNAME_KEY      1018
#define IDC_EDIT_PACK_HOSTNAME          1018
#define IDC_EDIT_PACK_PASSWORD_KEY      1019
#define IDC_EDIT_PACK_OK_BUTTON_NAME    1020
#define IDC_EDIT_PACK_ENDPASSWORD       1020
#define IDC_EDIT_PACK_OPERATE           1021
#define IDC_EDIT_PACK_SEND_CONTENT      1022
#define IDC_EDIT_PACK_SENDKEY           1022
#define IDC_EDIT_PACK_REMARK            1023
#define IDC_EDIT_PACK_ENDSEND           1023
#define IDC_EDIT_PACK_URL               1024
#define IDC_EDIT_PACK_PACKHEAD          1024
#define IDC_BUTTON_ADD                  1025
#define IDC_LIST1                       1026
#define IDC_LIST_WEB                    1026
#define IDC_LIST_FINDDLG_CAPTURE        1026
#define IDC_COMBO_WEB_OPERATEITEM       1027
#define IDC_COMBO_CODETYPE              1028
#define ID_BUTTON_TEST                  1029
#define IDC_LIST_LOGINSTAT              1030
#define ID_BUTTON_SAVE                  1031
#define IDC_COMBO_SETADAPTER            1032
#define IDC_EDIT1                       1033
#define IDC_EDIT_FINDDLG_PASSWORD       1034
#define IDC_EDIT_FINDDLG_SENDCONTENT    1035
#define IDC_RADIO3                      1036
#define IDC_RADIO4                      1037
#define IDC_RADIO5                      1038
#define IDC_RADIO6                      1039
#define IDC_RADIO7                      1040
#define IDC_RADIO_ONLINE_CAPTURE        1040
#define IDC_RADIO8                      1041
#define IDC_RADIO_OFFLINE_CAPTURE       1041
#define ID_BUTTONG_SET                  1042
#define IDC_LIST_PACK_INFO              1043
#define ID_BUTTON_STOP                  1044
#define IDC_RADIO1                      1045
#define IDC_RADIO_OFFLINE_CAPTUREFILE   1045
#define IDC_RADIO_FIND_ONLINE_PACK      1045
#define IDC_BUTTON_SELECT               1046
#define IDC_RADIO_OFFLINE_PACK          1046
#define IDC_CHECK_NOPACK                1047
#define IDC_CHECK_NOWEB                 1048
#define IDC_CHECK_NOMATCH               1049
#define IDC_CHECK_CLEAR_INTERNET        1050
#define IDC_CHECK_CLEAE_COOKIE          1051
#define IDC_CHECK_CLEAR_COOKIE          1051
#define IDC_EDIT_FINDDLG_USERNAME       1052
#define IDC_BUTTON_SHOW_CAPTUREMODE     1053
#define IDC_BUTTON_STOP                 1053
#define IDC_BUTTON_FINDDLG_STOP         1053
#define IDC_BUTTON_FINDDLG_STARTCAPTURE 1054
#define IDC_COMBO_SET_ADAPTER           1056
#define IDC_COMBO_PACK_RULELEN          1057
#define IDC_EDIT_FIND_PACKRULELEN       1058
#define IDC_BUTTON_FINDDLG_SAVE         1059
#define IDC_BUTTON_MODIFY               1060
#define IDC_BUTTON_DELETE               1061
#define IDC_BUTTON_WEB_DELETE           1063
#define IDC_BUTTON_WEB_MODIFY           1064
#define IDC_BUTTON_WEB_ADD              1065
#define IDC_BUTTON_WEB_QUIT             1066
#define IDC_EDIT_FILTER_NUM             1067
#define IDC_EDIT_FILTER_HEAD_LEN        1068
#define IDC_TREE_SHOW_DOWNLOAD_PATH     1069
#define IDC_PROGRESS_DOWNLOAD_STATE     1070
#define IDC_STATIC_SHOW_MSG             1073
#define ID_BUTTON_UPDATA                1074
#define IDC_STATIC_SERVER_ID            1075
#define IDC_STATIC_CLIENT_ID            1076
#define IDC_EDIT_SUBCONTRACTING_NUM     1077
#define IDC_COMBO1                      1078
#define IDC_EDIT_VOICE_PORT             1079
#define ID_32771                        32771
#define ID_32772                        32772
#define IDR_MENU_WEBFILE                32773
#define IDR_MENU_PACKFILE               32774
#define ID_32775                        32775
#define ID_32776                        32776
#define ID_32777                        32777
#define IDR_MENU_LOGIN_TEST             32778
#define IDR_MENU_SEND_TEST              32779
#define IDR_                            32780
#define IDR_MENU_FIND_PACP              32781
#define ID_32782                        32782
#define ID_32783                        32783
#define ID_MEUN                         32784
#define ID_MENU                         32785
#define ID_MENU_DOWNLOAD                32786
#define ID_32787                        32787
#define ID_MUTEX                        32788
#define ID_MENU_DWON                    32789
#define ID_MENU_UPDATA_DOWNLOAD         32790
#define ID_32791                        32791
#define ID_MENU_VOICE                   32792

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        143
#define _APS_NEXT_COMMAND_VALUE         32793
#define _APS_NEXT_CONTROL_VALUE         1080
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
