// TestMenu2.idl : TestMenu2 的 IDL 源
//

// 此文件将由 MIDL 工具处理以
// 产生类型库(TestMenu2.tlb)和封送处理代码。

import "oaidl.idl";
import "ocidl.idl";

[
	object,
	uuid(D1AB33F0-A2C7-4102-B354-9BA0978C9C2B),
	dual,
	nonextensible,
	helpstring("ICCopyPathEx 接口"),
	pointer_default(unique)
]
interface ICCopyPathEx : IDispatch{
};
[
	uuid(82D04B6C-CA5C-472B-AB17-226BA153B9A9),
	version(1.0),
	helpstring("TestMenu2 1.0 类型库")
]
library TestMenu2Lib
{
	importlib("stdole2.tlb");
	[
		uuid(AF58A0BA-0313-4CFA-8BD0-6A5FEA45FD44),
		helpstring("CCopyPathEx Class")
	]
	coclass CCopyPathEx
	{
		[default] interface ICCopyPathEx;
	};
};
