// HardLink.idl : IDL source for HardLink.dll
//

// This file will be processed by the MIDL tool to
// produce the type library (HardLink.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";
	[
		object,
		uuid(3C06DFAD-062F-11D4-8D3B-919D46C1CE19),
		dual,
		helpstring("IHardLinkShlExt Interface"),
		pointer_default(unique)
	]
	interface IHardLinkShlExt : IDispatch
	{
	};

[
	uuid(3C06DFA0-062F-11D4-8D3B-919D46C1CE19),
	version(1.0),
	helpstring("HardLink 1.0 Type Library")
]
library HARDLINKLib
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");

	[
		uuid(3C06DFAE-062F-11D4-8D3B-919D46C1CE19),
		helpstring("HardLinkShlExt Class")
	]
	coclass HardLinkShlExt
	{
		[default] interface IHardLinkShlExt;
	};
};
