// MP3TagViewer.idl : IDL source for MP3TagViewer.dll
//

// This file will be processed by the MIDL tool to
// produce the type library (MP3TagViewer.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";
	[
		object,
		uuid(6E282F9A-28E3-486C-9C84-E2AAA3892980),
	
		helpstring("IMP3ColExt Interface"),
		pointer_default(unique)
	]
	interface IMP3ColExt : IUnknown
	{
	};

[
	uuid(E91A976E-1B6A-4BBB-8A2B-99B73CA6937D),
	version(1.0),
	helpstring("MP3TagViewer 1.0 Type Library")
]
library MP3TAGVIEWERLib
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");

	[
		uuid(AC146E80-3679-4BCA-9BE4-E36512573E6C),
		helpstring("MP3ColExt Class")
	]
	coclass MP3ColExt
	{
		[default] interface IMP3ColExt;
	};
};
