// SimpleExt.idl : SimpleExt 的 IDL 源
//

// 此文件将由 MIDL 工具处理以
// 产生类型库(SimpleExt.tlb)和封送处理代码。

import "oaidl.idl";
import "ocidl.idl";

[
	object,
	uuid(6B3A5833-6DB5-4FF0-A06E-631FB2761ECB),
	dual,
	nonextensible,
	helpstring("ISimpleShlExt 接口"),
	pointer_default(unique)
]
interface ISimpleShlExt : IDispatch{
};
[
	uuid(00A37D4A-FB74-4CB1-B254-5792EFF1CDE3),
	version(1.0),
	helpstring("SimpleExt 1.0 类型库")
]
library SimpleExtLib
{
	importlib("stdole2.tlb");
	[
		uuid(E1DB2EBA-6D14-4481-89A0-54B18BD8DA95),
		helpstring("SimpleShlExt Class")
	]
	coclass SimpleShlExt
	{
		[default] interface ISimpleShlExt;
	};
};
