// This file was generated by WTL subclass control wizard 
// TextView.cpp : Implementation of TextView

#include "stdafx.h"
#include "TextView.h"
#include ".\textview.h"

// TextView
CTextView::CTextView()
{
}

CTextView::~CTextView()
{
}

HRESULT STDMETHODCALLTYPE CTextView::CreateWnd(HWND hWndParent)
{
	if (NULL != Create(hWndParent,
							NULL,
							L"TextView",
							ES_AUTOVSCROLL| ES_AUTOHSCROLL|WS_HSCROLL|WS_VSCROLL|WS_CHILD|WS_VISIBLE|WS_CLIPCHILDREN|WS_CLIPSIBLINGS|ES_MULTILINE,
							WS_EX_CLIENTEDGE))
	{
		return S_OK;
	}
	
	//Ð´Èë´íÎóÐÅÏ¢
	//...
	ATLASSERT(0);

	return S_FALSE;
}


void CTextView::OnCopy(UINT codeNotify, UINT cmdID, VARIANT_BOOL *bHandle)
{
	Copy();
}

void CTextView::OnPaste(UINT codeNotify, UINT cmdID, VARIANT_BOOL *bHandle)
{
	Paste();
}

void CTextView::OnSelectAll(UINT codeNotify, UINT cmdID, VARIANT_BOOL *bHandle)
{
	this->SetSel(0, GetWindowTextLength());
}

void CTextView::OnClear(UINT codeNotify, UINT cmdID, VARIANT_BOOL *bHandle)
{
	int x;
	int y;

	this->GetSel(x, y);
	this->ReplaceSel(_T(""));
}


void CTextView::OnUndo(UINT codeNotify, UINT cmdID, VARIANT_BOOL *bHandle)
{
	Undo();
}


//void CTextView::OnFormatFont(UINT codeNotify, UINT cmdID, VARIANT_BOOL *bHandle)
//{
//	CFontDialog fd;
//	if (IDOK == fd.DoModal())
//	{
//		if (NULL != font.m_hFont)
//		{
//			font.DeleteObject();
//		}
//		font.CreateFontIndirect(&fd.m_lf);
//		SetFont(font, TRUE);
//	}
//
//}
//void CTextView::OnCut(UINT codeNotify, UINT cmdID, VARIANT_BOOL *bHandle)
//{
//	Cut();
//}


LRESULT CTextView::OnFormatFont(WORD wNotifyCode, WORD wID, HWND hWndCtl)
{
	CFontDialog fd;
	if (IDOK == fd.DoModal())
	{
		if (NULL != font.m_hFont)
		{
			font.DeleteObject();
		}
		font.CreateFontIndirect(&fd.m_lf);
		SetFont(font, TRUE);
	}

	return 0;
}


LRESULT CTextView::OnEditCut(WORD wNotifyCode, WORD wID, HWND hWndCtl)
{
	Cut();
	return 0;
}
