#pragma once

template <class T>
class CProxy_IArtCommandBarsEvents : public IConnectionPointImpl<T, &__uuidof( _IArtCommandBarsEvents ), CComDynamicUnkArray>
{
	//Warning this class will  be regenerated by the wizard.
public:
};
