// This file was generated by WTL Dialog wizard 
// MDIChildWindows.cpp : Implementation of CMDIChildWindows

#include "stdafx.h"
#include "MDIChildWindows.h"
#include "MDIFrame.h"
#include ".\mdichildwindows.h"
#include "atlcomcli.h"

// CMDIChildWindows
CMDIChildWindows::CMDIChildWindows()
{
}

CMDIChildWindows::~CMDIChildWindows()
{
}

LRESULT CMDIChildWindows::OnInitDialog(UINT uMsg, WPARAM wParam, LPARAM lParam, BOOL& bHandled)
{
	DoDataExchange();
	DlgResize_Init();

	InitListCtrl();
	DataToListCtrl();

	return 1;  // Let the system set the focus
}

LRESULT CMDIChildWindows::OnClickedOK(WORD wNotifyCode, WORD wID, HWND hWndCtl, BOOL& bHandled)
{
	DoDataExchange(TRUE);
	EndDialog(wID);


	return 0;
}

LRESULT CMDIChildWindows::OnClickedCancel(WORD wNotifyCode, WORD wID, HWND hWndCtl, BOOL& bHandled)
{
	EndDialog(wID);
	return 0;
}

LRESULT CMDIChildWindows::OnButActivate(WORD wNotifyCode, WORD wID, HWND hWndCtl)
{

	return 0;
}

LRESULT CMDIChildWindows::OnButSave(WORD wNotifyCode, WORD wID, HWND hWndCtl)
{

	return 0;
}


LRESULT CMDIChildWindows::OnIdok(WORD wNotifyCode, WORD wID, HWND hWndCtl)
{

	return 0;
}


int CMDIChildWindows::InitListCtrl(void)
{
	m_wndListCtrl.AddColumn(L"Name", 0);
	m_wndListCtrl.AddColumn(L"Path", 1);

	return 0;
}


int CMDIChildWindows::DataToListCtrl(void)
{
	//IMDIChildFrames *_lpChildFrames;
	CComQIPtr<IMDIChildFrames, &IID_IMDIChildFrames> _lpChildFrames;

	IEnumVARIANT *_lpEnumVar;
	HRESULT hr = 0;
	VARIANT rgVar;
	ULONG CeltFetched = 0;
	IMDIChildFrame *lpChildFrame = NULL;
	CComBSTR _bstrTitle;
	int nItem = 0;

	g_MDIFrame->get_MDIChildFrames((IDispatch**)&_lpChildFrames);

	hr = _lpChildFrames->get__NewEnum((IUnknown**)&_lpEnumVar);
	if (FAILED(hr))
	{
		return 1;
	}

	_lpEnumVar->Reset();

	while (_lpEnumVar->Next(1, &rgVar, &CeltFetched)==S_OK && CeltFetched)
	{
		lpChildFrame = (IMDIChildFrame*)*rgVar.ppdispVal;
		ATLASSERT(NULL != lpChildFrame);
		lpChildFrame->get_Title(&_bstrTitle);
		m_wndListCtrl.InsertItem(nItem, _bstrTitle);
		nItem ++;
	}

	return 0;
}
