// CopyPath.idl : CopyPath 的 IDL 源
//

// 此文件将由 MIDL 工具处理以
// 产生类型库(CopyPath.tlb)和封送处理代码。

import "oaidl.idl";
import "ocidl.idl";

[
	object,
	uuid(B7C740E6-3009-4A2A-835B-6C818799C0BD),
	dual,
	nonextensible,
	helpstring("ICCopyPathEx 接口"),
	pointer_default(unique)
]
interface ICCopyPathEx : IDispatch{
};
[
	uuid(32274133-B8EE-4545-B828-2F28E04994AA),
	version(1.0),
	helpstring("CopyPath 1.0 类型库")
]
library CopyPathLib
{
	importlib("stdole2.tlb");
	[
		uuid(0300C08C-FCC0-4534-BD38-7A0F76C21043),
		helpstring("CCopyPathEx Class")
	]
	coclass CCopyPathEx
	{
		[default] interface ICCopyPathEx;
	};
};
