// DirBkgndExt.idl : IDL source for DirBkgndExt.dll
//

// This file will be processed by the MIDL tool to
// produce the type library (DirBkgndExt.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";
	[
		object,
		uuid(6F6B303F-2EAD-4973-89EE-5FCEC7257962),
		dual,
		helpstring("IBkgndCtxMenuExt Interface"),
		pointer_default(unique)
	]
	interface IBkgndCtxMenuExt : IDispatch
	{
	};

[
	uuid(B377AEE3-6F79-4C28-A8EA-89E6A6BE8F45),
	version(1.0),
	helpstring("DirBkgndExt 1.0 Type Library")
]
library DIRBKGNDEXTLib
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");

	[
		uuid(9E5E1445-6CEA-4761-8E45-AA19F654571E),
		helpstring("BkgndCtxMenuExt Class")
	]
	coclass BkgndCtxMenuExt
	{
		[default] interface IBkgndCtxMenuExt;
	};
};
