//IMy.idl

//这一文件将被MIDL工具处理，以产生类型库类型库(***.tlb)和编组代码。

import "oaidl.idl";
import "ocidl.idl";
[
	object,
	uuid(FAEAE6B7-67BE-42a4-A318-3256781E945A),
	helpstring("IMy Interface"),	
	pointer_default(unique)
]
interface IMy : IUnknown
{	
	HRESULT Add([in]int x1,[in]int x2);
	HRESULT Get([out,retval]int * pret);	
};

[
	uuid(01147C39-9DA0-4f7f-B525-D129745AAD1E),
	helpstring("IMy2 Interface"),
	object,
	pointer_default(unique)
]
interface IMy2 : IUnknown
{
	HRESULT SayHello([out,retval]CHAR * pret);	
};
		
[
	uuid(CA3B37EA-E44A-49b8-9729-6E9222CAE844),
	version(1.0),
	helpstring("My Type Library")
]
library SSZLib
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");


	[
		uuid(3BCFE27E-C88D-453C-8C94-F5F7B97E7841),
		helpstring("SSZ Class")
	]
	coclass SSZ
	{
		[default] interface IMy;
		interface IMy2;
	};
};
