//IMy.idl

//这一文件将被MIDL工具处理，以产生类型库类型库(***.tlb)和编组代码。

import "oaidl.idl";
import "ocidl.idl";
[
	object,
	uuid(D77FDBC5-E7D5-48aa-986F-E5D58F57F59F),
	helpstring("IMy Interface"),	
	pointer_default(unique)
]
interface IMy : IUnknown
{	
	HRESULT Add([in]int x1,[in]int x2);
	HRESULT Get([out,retval]int * pret);	
};

[
	uuid(0F30D079-C236-4baf-8869-28AF39DAC365),
	helpstring("IMy2 Interface"),
	object,
	pointer_default(unique)
]
interface IMy2 : IUnknown
{
	HRESULT SayHello([out,retval]CHAR * pret);	
};
		
[
	uuid(5BC9017F-F3FB-4f7b-BE3B-EA44F1D10180),
	version(1.0),
	helpstring("My Type Library")
]
library SSZLib
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");


	[
		uuid(A738E0FE-EF11-482a-AFE2-1164E4749F25),
		helpstring("SSZ Class")
	]
	coclass SSZ
	{
		[default] interface IMy;
		interface IMy2;
	};
};
