// Simple2.idl : Simple2 的 IDL 源
//

// 此文件将由 MIDL 工具处理以
// 产生类型库(Simple2.tlb)和封送处理代码。

import "oaidl.idl";
import "ocidl.idl";

[
	object,
	uuid(9C0330E2-D53F-43E3-B899-97B94BF76B64),
	helpstring("IFun 接口"),
	pointer_default(unique)
]
interface IFun : IUnknown{
	[helpstring("方法Add")] HRESULT Add([in] LONG n1, [in] LONG n2, [out,retval] LONG* pVal);
	[helpstring("方法Cat")] HRESULT Cat([in] BSTR s1, [in] BSTR s2, [out,retval] BSTR* pVal);
};
[
	uuid(A7F9A697-9F48-41AE-A697-3A9BE77582CC),
	version(1.0),
	helpstring("Simple2 1.0 类型库")
]
library Simple2Lib
{
	importlib("stdole2.tlb");
	[
		uuid(CA61C492-9AD3-469F-B75A-C021E03F21FB),
		helpstring("Fun Class")
	]
	coclass Fun
	{
		[default] interface IFun;
	};
};
