// PiSvr.idl : PiSvr 的 IDL 源
//

// 此文件将由 MIDL 工具处理以
// 产生类型库(PiSvr.tlb)和封送处理代码。

import "oaidl.idl";
import "ocidl.idl";

[
	uuid(E7FB81F5-B2EE-4455-BDD1-B09AA6402656),
	version(1.0),
	helpstring("PiSvr 1.0 类型库")
]
library PiSvrLib
{
	importlib("stdole2.tlb");
};
