// BmpViewerExt.idl : IDL source for BmpViewerExt.dll
//

// This file will be processed by the MIDL tool to
// produce the type library (BmpViewerExt.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";
	[
		object,
		uuid(6279F517-5097-44F8-A52F-F182935C485C),
		dual,
		helpstring("IBmpCtxMenuExt Interface"),
		pointer_default(unique)
	]
	interface IBmpCtxMenuExt : IDispatch
	{
	};

[
	uuid(1BEB890A-731F-46B7-88E4-5D71871705CF),
	version(1.0),
	helpstring("BmpViewerExt 1.0 Type Library")
]
library BMPVIEWEREXTLib
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");

	[
		uuid(D6F469CD-3DC7-408F-BB5F-74A1CA2647C9),
		helpstring("BmpCtxMenuExt Class")
	]
	coclass BmpCtxMenuExt
	{
		[default] interface IBmpCtxMenuExt;
	};
};
