CREATE TABLE [dbo].[Test](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[sPhone] [varchar](50) COLLATE Chinese_PRC_CI_AS NULL,
	[sPwd] [varchar](50) COLLATE Chinese_PRC_CI_AS NULL,
 CONSTRAINT [PK_Test] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]