// GncShellExt.idl : IDL source for GncShellExt.dll
//
// Author: Glenn Carr (GlennCarr@email.com)
// Please send any bugs or fixes to GlennCarr@email.com.
//

// This file will be processed by the MIDL tool to
// produce the type library (GncShellExt.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";
	[
		object,
		uuid(303FEFEF-6ABA-11D3-90E4-0090272D53E3),
		dual,
		helpstring("ICopyPathExt Interface"),
		pointer_default(unique)
	]
	interface ICopyPathExt : IDispatch  // not used
	{
	};

[
	uuid(303FEFE3-6ABA-11D3-90E4-0090272D53E3),
	version(1.0),
	helpstring("GncShellExt 1.0 Type Library")
]
library GNCSHELLEXTLib
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");

	[
		uuid(303FEFF0-6ABA-11D3-90E4-0090272D53E3),
		helpstring("CopyPathExt Class")
	]
	coclass CopyPathExt
	{
		[default] interface ICopyPathExt;	// not used
	};
};
