// Simple7.idl : Simple7.dll 的类型库源
// 此文件将由 MIDL 编译器处理以产生
// 类型库(Simple7.tlb)。

#include "olectl.h"
[ uuid(FA4F0B17-C60D-46A6-B4C5-A4F133B1F273), version(1.0) ]
library Simple7
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");

	//  DispSimple 的主调度接口
		
	[ uuid(F9E6A98A-B849-475F-8D55-F951D86FCD37) ]
	dispinterface IDispSimple
	{
		properties:
		methods:
		[id(1), helpstring("方法Add")] LONG Add(LONG n1, LONG n2);
		[id(2), helpstring("方法Upper")] BSTR Upper(BSTR str);
	};

	//  DispSimple 的类信息

	[ uuid(C374DBA9-C292-42DA-B146-241748359875) ]
	coclass DispSimple
	{
		[default] dispinterface IDispSimple;
	};
};
