// This file was generated by WTL Dialog wizard 
// AboutCOMFrame.cpp : Implementation of CAboutCOMFrame

#include "stdafx.h"
#include "AboutCOMFrame.h"

// CAboutCOMFrame
CAboutCOMFrame::CAboutCOMFrame()
{
}

CAboutCOMFrame::~CAboutCOMFrame()
{
}

LRESULT CAboutCOMFrame::OnInitDialog(UINT uMsg, WPARAM wParam, LPARAM lParam, BOOL& bHandled)
{
	DoDataExchange();
	CString strInfo=L"\
使用COM技术设计的《COM应用程序框架》，目前这个版是试验版本。\r\n\r\n\
以下地点拥有更多的信息：\r\n\
	http://blog.csdn.net/NetLinux\r\n\
	http://www.willspace.net\r\n\r\n\
如果您有更好的意见请用ytf1978@163.com电子信箱与作者联系。\r\n";
	m_wndEditInfo.SetWindowText(strInfo);

	return 1;  // Let the system set the focus
}


LRESULT CAboutCOMFrame::OnClickedOK(WORD wNotifyCode, WORD wID, HWND hWndCtl, BOOL& bHandled)
{
	DoDataExchange(TRUE);
	EndDialog(wID);
	return 0;
}


LRESULT CAboutCOMFrame::OnClickedCancel(WORD wNotifyCode, WORD wID, HWND hWndCtl, BOOL& bHandled)
{
	EndDialog(wID);
	return 0;
}
