// ArtFrame.idl : IDL source for ArtFrame
//

// This file will be processed by the MIDL tool to
// produce the type library (ArtFrame.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";


//----------------------------------------------------------------------
typedef 
[
	uuid(41F5D07A-04F6-11DB-B3CC-005056C00008),
	helpstring(""),
]
enum artCommandBarType {
    artCommandBarTypePopup = 10,
    artCommandBarTypeToolbar = 23,
    artCommandBarTypeMenu = 24
}artCommandBarType;

//-----------------------------------------------------------------------
typedef 
[
	uuid(1ED1D01A-E88C-4963-AD4F-C4775D068865),
	helpstring(""),
]
enum artCommandItemStyle
{
    msoButtonAutomatic = 0,
    msoButtonIcon = 1,
    msoButtonCaption = 2,
    msoButtonIconAndCaption = 3,
    //msoButtonIconAndWrapCaption = 7,
    msoButtonIconAndCaptionBelow = 11,
    //msoButtonWrapCaption = 14,
    //msoButtonIconAndWrapCaptionBelow = 15
}artCommandItemStyle;

//-----------------------------------------------------------------------
//定义数据视图
[
	object,
	uuid(E2E319A4-D764-4dc1-95CD-C92D3754D95B),
	dual,
	nonextensible,
	helpstring("IDataView Interface"),
	pointer_default(unique)
]
interface IDataView : IDispatch {
	[id(1), helpstring("method NotifyCommand")] HRESULT NotifyCommand(UINT codeNotify, UINT cmdID, VARIANT_BOOL *bHandle);
	[id(2), helpstring("method GetWnd")] HRESULT GetWnd(HWND *hWnd);
	[id(3), helpstring("nType WM_ACTIVATE")] HRESULT OnActiveWindow(UINT nType);
	[id(4), helpstring("nType OnCloseWindow")] HRESULT OnCloseWindow(VARIANT_BOOL *vbClose);
	[id(5), helpstring("nType CreateWnd")] HRESULT CreateWnd(HWND hWndParent);
};

//-----------------------------------------------------------------------
[
	object,
	uuid(3B8C7933-4F37-4d83-9107-CF68586155E2),
	dual,
	nonextensible,
	helpstring("_COMFrameDispObj Interface"),
	pointer_default(unique)
]
interface _COMFrameDispObj : IDispatch{
	[propget, id(50), helpstring("property COMMDIFrame")] HRESULT COMMDIFrame([out, retval] IDispatch** pVal);
};


//-----------------------------------------------------------------------

typedef
[
	uuid(C90C84B4-FA10-11DA-AB3A-005056C00008),
	helpstring("CreateMDIStruct"),
]
struct CreateMDIStruct
{
	UINT cbSize;
	DWORD mask;
	LPWSTR lpszWindowName;
	HMENU hMenu;
	LPARAM lParam;	
}CreateMDIStruct;

typedef CreateMDIStruct* LPCreateMDIStruct;

///////////////////////////////////////////////////////////////////////////
[
	object,
	uuid(D3137FF6-206B-4767-A905-5D252B3D9325),
	dual,
	nonextensible,
	helpstring("IMDIFrame Interface"),
	pointer_default(unique)
]
interface IMDIFrame : _COMFrameDispObj{
	[id(1), helpstring("method Run")] HRESULT Run(void);	  
	[id(2), helpstring("method CreateWnd")] HRESULT CreateWnd(CreateMDIStruct* lpMDIStruct);
	[id(3), helpstring("method Quit")] HRESULT Quit(void);
	[id(4), helpstring("method ShowMe")] HRESULT ShowMe(VARIANT_BOOL vbShow);
	[propget, id(5), helpstring("property MDIChildFrames")] HRESULT MDIChildFrames([out, retval] IDispatch** pVal);
	[id(52), helpstring("method AboutCOMFrame")] HRESULT AboutCOMFrame(void);
	[id(53), helpstring("method MDIWindows")] HRESULT MDIWindows(void);
};


[
	object,
	uuid(A61BB8F9-6141-427C-AA31-CC4888335E51),
	dual,
	nonextensible,
	helpstring("IMDIChildFrame Interface"),
	pointer_default(unique)
]
interface IMDIChildFrame : _COMFrameDispObj{
	[id(4), helpstring("添加一个了窗口视图")] HRESULT PushDataView(IDataView* lpDataView);
	[id(6), helpstring("移出一个子窗口视图")] HRESULT PopDataView([in] IDataView* lpCW);
	[propget, id(7), helpstring("property ActiveChildWindow")] HRESULT ActiveChildWindow([out, retval] IDataView** pVal);
	[propput, id(7), helpstring("property ActiveChildWindow")] HRESULT ActiveChildWindow([in] IDataView* newVal);
	[propget, id(51), helpstring("property Title")] HRESULT Title([out, retval] BSTR* pVal);
	[propput, id(51), helpstring("property Title")] HRESULT Title([in] BSTR newVal);
	[propget, id(52), helpstring("property CommandBars")] HRESULT CommandBars([out, retval] IDispatch** pVal);
};


[
	object,
	uuid(DBDC4265-324B-4E01-9BBE-8AB76FBB8CF6),
	dual,
	nonextensible,
	helpstring("IMDIChildFrames Interface"),
	pointer_default(unique)
]

interface IMDIChildFrames : _COMFrameDispObj{
	[propget, id(2)] HRESULT Count([out, retval] long *pVal);
	[propget, id(4), restricted, hidden] HRESULT _NewEnum([out, retval] IUnknown* *pVal);
    [id(DISPID_VALUE), propget]  HRESULT Item( [in] long Index, [out, retval] VARIANT* pVal);
	[id(7), helpstring("method CreateChildFrame")] HRESULT CreateChildFrame([in] IDataView* lpdv, [out]IMDIChildFrame** lpcf);
};



[
	uuid(28462839-FA53-4A4C-A776-676CD60D4238),
	version(1.0),
	helpstring("ArtFrame 1.0 Type Library")
]
library ArtFrameLib
{
	importlib("stdole2.tlb");
	[
		uuid(62F13529-A28A-4ECB-ACD6-14192AF1205D),
		helpstring("_CommandButtonEvents Interface")
	]
	dispinterface _CommandButtonEvents
	{
		properties:
		methods:
		[id(1), helpstring("method NotifyCommand")] HRESULT NotifyCommand(UINT codeNotify, UINT cmdID, VARIANT_BOOL *bHandle);
	};

	[
		uuid(866BD9AA-8EC6-45D1-B1D2-55B1E8967E37),
		helpstring("_IMDIFrameEvents Interface")
	]
	dispinterface _IMDIFrameEvents
	{
		properties:
		methods:
		[id(1), helpstring("method OnQuit")] HRESULT OnQuit(VARIANT_BOOL *vbQuit);
		[id(2), helpstring("method NotifyCommand")] HRESULT NotifyCommand(LONG codeNotify, LONG cmdID, VARIANT_BOOL *bHandle);
	};
	[
		uuid(B092D48B-B0B7-4AFE-9010-986274A78673),
		helpstring("MDIFrame Class")
	]
	coclass MDIFrame
	{
		[default] interface IMDIFrame;
		[default, source] dispinterface _IMDIFrameEvents;
	};


	[
		uuid(5BE13374-8203-4A09-8A34-CAE92D2747A0),
		helpstring("_IMDIChildFrameEvents Interface")
	]
	dispinterface _IMDIChildFrameEvents
	{
		properties:
		methods:
		[id(1), helpstring("method NotifyCommand")] HRESULT NotifyCommand(UINT codeNotify, UINT cmdID, VARIANT_BOOL *bHandle);
	};
	[
		uuid(47B924E4-4E16-4DB9-AE43-3F0144BE0DD2),
		helpstring("MDIChildFrame Class")
	]
	coclass MDIChildFrame
	{
		[default] interface IMDIChildFrame;
		[default, source] dispinterface _IMDIChildFrameEvents;
	};
	[
		uuid(9462FE98-891A-463D-9B6D-CDEA80462BB2),
		helpstring("MDIChildFrames Class")
	]
	coclass MDIChildFrames
	{
		[default] interface IMDIChildFrames;
	};
};
