// TxtInfo.idl : IDL source for TxtInfo.dll
//

// This file will be processed by the MIDL tool to
// produce the type library (TxtInfo.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";
	[
		object,
		uuid(F4D78AE0-05AB-11D4-8D3B-444553540000),
		dual,
		helpstring("ITxtInfoShlExt Interface"),
		pointer_default(unique)
	]
	interface ITxtInfoShlExt : IDispatch
	{
	};

[
	uuid(29C6936B-0596-11D4-8D3B-B4BAC1C08C1E),
	version(1.0),
	helpstring("TxtInfo 1.0 Type Library")
]
library TXTINFOLib
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");

	[
		uuid(F4D78AE1-05AB-11D4-8D3B-444553540000),
		helpstring("TxtInfoShlExt Class")
	]
	coclass TxtInfoShlExt
	{
		[default] interface ITxtInfoShlExt;
	};
};
